### ISSUE TITLE
When you say HP System Event Utility, do you mean the application or the driver.

### ISSUE THREAD

**Issue by oraant** [jingyu9575/remap-omen-key#5]
If I search `HP System Event Utility` when pressing Windows Button, I opened an application like this:
![image](https://user-images.githubusercontent.com/12079340/58680530-b5cfaf80-839a-11e9-82e9-794cc87d019b.png)

But I can't find `HKEY_CURRENT_USER\Software\HP\HP System Event` in regedit, and doesn't have any program like `C:\Program Files (x86)\HP\HP System Event\HPMSGSVC.exe`

So I guess maybe what you said is a driver?

**Comment by jingyu9575** [comment]
Yes it is the driver. Try this installer: [sp81404](http://ftp.hp.com/pub/softpaq/sp81001-81500/sp81404.exe)

**Comment by oraant** [comment]
> Yes it is the driver. Try this installer: [sp81404](http://ftp.hp.com/pub/softpaq/sp81001-81500/sp81404.exe)

Well, I tried your driver, but still failed, no `HP System Event` in regedit.
Truns out it's the same application with the picture I posted before.

Then I uninstalled my native app, and installed your version, guess what!
I lost my `HP System Event Utility` APP, press `OMEN` key has no response, and still can't find `HP System Event` in regedit!

I have been tortured by this problem for six month, it's driving me crazy..

**Comment by jingyu9575** [comment]
Not sure what's happening here. The "系统信息" dialog you opened is `SysInfoEx.exe` in the same driver, so I'd suggest trying to get your native driver back, and use Task Manager or disk search to find this app. `HPMSGSVC.exe` should be in the same folder.

![图片](https://user-images.githubusercontent.com/8923139/61176052-ba6bc280-a5ec-11e9-86ff-cb7b5335c28a.png)

**Comment by hollowstrawberry** [comment]
HPMSGSVC.exe doesn't exist in that folder.
