### ISSUE TITLE
Does't work

### ISSUE THREAD

**Issue by 127p** [jingyu9575/remap-omen-key#8]
Hi, I read the last update that indicates that you have to have the HP System Event Utility with HPMSGSVC.exe, but I can't find a version with that executable, could you help me with a version that you use to make this work?

Thank you

**Comment by jingyu9575** [comment]
[This one](http://ftp.hp.com/pub/softpaq/sp81001-81500/sp81404.exe) is what I am using.

The new Windows 10 app version does not work. I've tried to debug it but have not got progress yet.

**Comment by 127p** [comment]
Thanks!
